name: Create Release with Submodules

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Force update submodules
        run: git submodule update --init --recursive

      - name: Ensure submodule branches are correct
        run: git submodule foreach 'git checkout main || true'

      - name: List files to verify submodules
        run: ls -R

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: .
